# Generated by Django 5.2 on 2025-05-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorData',
            new_name='SensorReading',
        ),
    ]
